apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-server
  namespace: sns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-server
  template:
    metadata:
      labels:
        app: image-server
    spec:
      volumes:
        - name: image-volume
          emptyDir: {}
      containers:
        - name: image-container
          image: jheo/msa-image-server:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - name: image-volume
              mountPath: /images
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 10"]
